<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Services\Interface\24ro0u1b.fbe~" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElectonShop.Infra.Data\ElectonShop.Infra.Data.csproj" />
  </ItemGroup>

</Project>
